### ISSUE TITLE
Add the possibility to loop the streaming of an avro file 

### ISSUE THREAD

**Issue by johnsout** [nachosoto93/SimpleAvroKafkaProducer#2]
The application should be able to start the streaming again once it reaches the end of an avro file.

For example:

java -jar application.jar -loop avro.file localhost:9091 topic

Once it reaches the end of an avro file, the application should start again from the beginning of the file if the -loop flag is activated at its execution.

**Comment by ignaciosoto93** [comment]
Solved. Ex:
java -jar simpleAvroKafkaTopic-0.0.1-SNAPSHOT.jar /Users/nachosoto/Downloads/cdn.avro localhost:9092 test -loop
